[package]
name = "aoc25"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
regex = "1.12.2"
chrono = "0.4.42"
log = "0.4.29"
chrono-tz = "0.10.4"
image = "0.24"
ab_glyph = "0.2"



